/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppLessonsRouteImport } from './routes/app.lessons'
import { Route as AppAssessmentsIndexRouteImport } from './routes/app.assessments.index'
import { Route as AppClassesIndexRouteImport } from './routes/app.classes.index'
import { Route as AppClassesClassIdRouteImport } from './routes/app.classes.$classId'
import { Route as AppStudentsIndexRouteImport } from './routes/app.students.index'
import { Route as AppStudentsStudentIdRouteImport } from './routes/app.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsIndexRoute = AppAssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesIndexRoute = AppClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesClassIdRoute = AppClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/lessons': typeof AppLessonsRoute
  '/app/': typeof AppIndexRoute
  '/app/classes/$classId': typeof AppClassesClassIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/assessments/': typeof AppAssessmentsIndexRoute
  '/app/classes/': typeof AppClassesIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/lessons': typeof AppLessonsRoute
  '/app': typeof AppIndexRoute
  '/app/classes/$classId': typeof AppClassesClassIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/assessments': typeof AppAssessmentsIndexRoute
  '/app/classes': typeof AppClassesIndexRoute
  '/app/students': typeof AppStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/lessons': typeof AppLessonsRoute
  '/app/': typeof AppIndexRoute
  '/app/classes/$classId': typeof AppClassesClassIdRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/app/assessments/': typeof AppAssessmentsIndexRoute
  '/app/classes/': typeof AppClassesIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/lessons'
    | '/app/'
    | '/app/classes/$classId'
    | '/app/students/$studentId'
    | '/app/assessments/'
    | '/app/classes/'
    | '/app/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/lessons'
    | '/app'
    | '/app/classes/$classId'
    | '/app/students/$studentId'
    | '/app/assessments'
    | '/app/classes'
    | '/app/students'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/lessons'
    | '/app/'
    | '/app/classes/$classId'
    | '/app/students/$studentId'
    | '/app/assessments/'
    | '/app/classes/'
    | '/app/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lessons': {
      id: '/app/lessons'
      path: '/lessons'
      fullPath: '/app/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments/': {
      id: '/app/assessments/'
      path: '/assessments'
      fullPath: '/app/assessments/'
      preLoaderRoute: typeof AppAssessmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes/': {
      id: '/app/classes/'
      path: '/classes'
      fullPath: '/app/classes/'
      preLoaderRoute: typeof AppClassesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes/$classId': {
      id: '/app/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/app/classes/$classId'
      preLoaderRoute: typeof AppClassesClassIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/': {
      id: '/app/students/'
      path: '/students'
      fullPath: '/app/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/$studentId': {
      id: '/app/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/app/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLessonsRoute: typeof AppLessonsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClassesClassIdRoute: typeof AppClassesClassIdRoute
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
  AppAssessmentsIndexRoute: typeof AppAssessmentsIndexRoute
  AppClassesIndexRoute: typeof AppClassesIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLessonsRoute: AppLessonsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClassesClassIdRoute: AppClassesClassIdRoute,
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
  AppAssessmentsIndexRoute: AppAssessmentsIndexRoute,
  AppClassesIndexRoute: AppClassesIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
